# any changes to this file MUST be validated prior to comitting!!
#
# Powershell: Invoke-RestMethod -Uri https://codecov.io/validate -Body (Get-Content -Raw -LiteralPath .\codecov.yml) -Method post
# shell: curl --data-binary @codecov.yml https://codecov.io/validate
#
codecov:
  branch: main
  require_ci_to_pass: no
  notify:
    wait_for_ci: no
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1% # code coverage can drop by 1% and still be successful
        if_ci_failed: success 
        informational: true  # if true, status will pass regardless regardless of other settings
    patch:
      default:
        target: auto
        threshold: 1% # code coverage can drop by 1% and still be successful
        if_ci_failed: success 
        informational: true  # if true, status will pass regardless regardless of other settings
comment:
  layout: "reach, diff, files" # change to "reach, diff, flags, files" if we start using flags
  behavior: default # new comment will be posted or existing comment will be edited
