configurationDefinitions:
  - platform: KUBERNETESCLUSTER
    description: Dotnet agent configuration
    type: agent-config
    version: 1.2.0
    schema: ../src/Agent/NewRelic/Agent/Core/Config/Configuration.xsd
    format: xml
    schemaFormat: xsd
