// ------------------------------------------------------------------------------
//  <auto-generated>
//    Generated by Xsd2Code. Version 3.6.0.0
//    <NameSpace>NewRelic.Agent.Core.Config</NameSpace><Collection>List</Collection><codeType>CSharp</codeType><EnableDataBinding>False</EnableDataBinding><EnableLazyLoading>False</EnableLazyLoading><TrackingChangesEnable>False</TrackingChangesEnable><GenTrackingClasses>False</GenTrackingClasses><HidePrivateFieldInIDE>False</HidePrivateFieldInIDE><EnableSummaryComment>False</EnableSummaryComment><VirtualProp>False</VirtualProp><PascalCase>False</PascalCase><BaseClassName>EntityBase</BaseClassName><IncludeSerializeMethod>False</IncludeSerializeMethod><UseBaseClass>False</UseBaseClass><GenBaseClass>False</GenBaseClass><GenerateCloneMethod>False</GenerateCloneMethod><GenerateDataContracts>False</GenerateDataContracts><CodeBaseTag>Net20</CodeBaseTag><SerializeMethodName>Serialize</SerializeMethodName><DeserializeMethodName>Deserialize</DeserializeMethodName><SaveToFileMethodName>SaveToFile</SaveToFileMethodName><LoadFromFileMethodName>LoadFromFile</LoadFromFileMethodName><GenerateXMLAttributes>False</GenerateXMLAttributes><OrderXMLAttrib>False</OrderXMLAttrib><EnableEncoding>False</EnableEncoding><AutomaticProperties>False</AutomaticProperties><GenerateShouldSerialize>False</GenerateShouldSerialize><DisableDebug>False</DisableDebug><PropNameSpecified>Default</PropNameSpecified><Encoder>UTF8</Encoder><CustomUsings></CustomUsings><ExcludeIncludedTypes>False</ExcludeIncludedTypes><InitializeFields>All</InitializeFields><GenerateAllTypes>True</GenerateAllTypes>
//  </auto-generated>
// ------------------------------------------------------------------------------
namespace NewRelic.Agent.Core.Config
{
    using System;
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System.Collections;
    using System.Xml.Schema;
    using System.ComponentModel;
    using System.Collections.Generic;
    
    
    public partial class configuration
    {
        
        private configurationService serviceField;
        
        private configurationApplication applicationField;
        
        private configurationLog logField;
        
        private configurationInstrumentation instrumentationField;
        
        private configurationAttributes attributesField;
        
        private configurationParameterGroups parameterGroupsField;
        
        private configurationRequestParameters requestParametersField;
        
        private configurationAnalyticsEvents analyticsEventsField;
        
        private configurationCustomEvents customEventsField;
        
        private configurationTransactionEvents transactionEventsField;
        
        private configurationDataTransmission dataTransmissionField;
        
        private configurationTransactionTracer transactionTracerField;
        
        private configurationDatastoreTracer datastoreTracerField;
        
        private configurationCrossApplicationTracer crossApplicationTracerField;
        
        private configurationHighSecurity highSecurityField;
        
        private configurationLiveInstrumentation liveInstrumentationField;
        
        private configurationStripExceptionMessages stripExceptionMessagesField;
        
        private configurationSlowSql slowSqlField;
        
        private configurationErrorCollector errorCollectorField;
        
        private configurationBrowserMonitoring browserMonitoringField;
        
        private configurationApplicationPools applicationPoolsField;
        
        private List<string> threadProfilingField;
        
        private string labelsField;
        
        private List<configurationAdd> appSettingsField;
        
        private configurationUtilization utilizationField;
        
        private bool agentEnabledField;
        
        private bool rootAgentEnabledField;
        
        private int maxStackTraceLinesField;
        
        private bool debugAgentField;
        
        private bool threadProfilingEnabledField;
        
        private bool crossApplicationTracingEnabledField;
        
        private configurationTimingPrecision timingPrecisionField;
        
        public configuration()
        {
            this.utilizationField = new configurationUtilization();
            this.appSettingsField = new List<configurationAdd>();
            this.threadProfilingField = new List<string>();
            this.applicationPoolsField = new configurationApplicationPools();
            this.browserMonitoringField = new configurationBrowserMonitoring();
            this.errorCollectorField = new configurationErrorCollector();
            this.slowSqlField = new configurationSlowSql();
            this.stripExceptionMessagesField = new configurationStripExceptionMessages();
            this.liveInstrumentationField = new configurationLiveInstrumentation();
            this.highSecurityField = new configurationHighSecurity();
            this.crossApplicationTracerField = new configurationCrossApplicationTracer();
            this.datastoreTracerField = new configurationDatastoreTracer();
            this.transactionTracerField = new configurationTransactionTracer();
            this.dataTransmissionField = new configurationDataTransmission();
            this.transactionEventsField = new configurationTransactionEvents();
            this.customEventsField = new configurationCustomEvents();
            this.analyticsEventsField = new configurationAnalyticsEvents();
            this.requestParametersField = new configurationRequestParameters();
            this.parameterGroupsField = new configurationParameterGroups();
            this.attributesField = new configurationAttributes();
            this.instrumentationField = new configurationInstrumentation();
            this.logField = new configurationLog();
            this.applicationField = new configurationApplication();
            this.serviceField = new configurationService();
            this.agentEnabledField = true;
            this.rootAgentEnabledField = false;
            this.maxStackTraceLinesField = 80;
            this.debugAgentField = false;
            this.threadProfilingEnabledField = true;
            this.crossApplicationTracingEnabledField = true;
            this.timingPrecisionField = configurationTimingPrecision.low;
        }
        
        public configurationService service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
        
        public configurationApplication application
        {
            get
            {
                return this.applicationField;
            }
            set
            {
                this.applicationField = value;
            }
        }
        
        public configurationLog log
        {
            get
            {
                return this.logField;
            }
            set
            {
                this.logField = value;
            }
        }
        
        public configurationInstrumentation instrumentation
        {
            get
            {
                return this.instrumentationField;
            }
            set
            {
                this.instrumentationField = value;
            }
        }
        
        public configurationAttributes attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
        
        public configurationParameterGroups parameterGroups
        {
            get
            {
                return this.parameterGroupsField;
            }
            set
            {
                this.parameterGroupsField = value;
            }
        }
        
        public configurationRequestParameters requestParameters
        {
            get
            {
                return this.requestParametersField;
            }
            set
            {
                this.requestParametersField = value;
            }
        }
        
        public configurationAnalyticsEvents analyticsEvents
        {
            get
            {
                return this.analyticsEventsField;
            }
            set
            {
                this.analyticsEventsField = value;
            }
        }
        
        public configurationCustomEvents customEvents
        {
            get
            {
                return this.customEventsField;
            }
            set
            {
                this.customEventsField = value;
            }
        }
        
        public configurationTransactionEvents transactionEvents
        {
            get
            {
                return this.transactionEventsField;
            }
            set
            {
                this.transactionEventsField = value;
            }
        }
        
        public configurationDataTransmission dataTransmission
        {
            get
            {
                return this.dataTransmissionField;
            }
            set
            {
                this.dataTransmissionField = value;
            }
        }
        
        public configurationTransactionTracer transactionTracer
        {
            get
            {
                return this.transactionTracerField;
            }
            set
            {
                this.transactionTracerField = value;
            }
        }
        
        public configurationDatastoreTracer datastoreTracer
        {
            get
            {
                return this.datastoreTracerField;
            }
            set
            {
                this.datastoreTracerField = value;
            }
        }
        
        public configurationCrossApplicationTracer crossApplicationTracer
        {
            get
            {
                return this.crossApplicationTracerField;
            }
            set
            {
                this.crossApplicationTracerField = value;
            }
        }
        
        public configurationHighSecurity highSecurity
        {
            get
            {
                return this.highSecurityField;
            }
            set
            {
                this.highSecurityField = value;
            }
        }
        
        public configurationLiveInstrumentation liveInstrumentation
        {
            get
            {
                return this.liveInstrumentationField;
            }
            set
            {
                this.liveInstrumentationField = value;
            }
        }
        
        public configurationStripExceptionMessages stripExceptionMessages
        {
            get
            {
                return this.stripExceptionMessagesField;
            }
            set
            {
                this.stripExceptionMessagesField = value;
            }
        }
        
        public configurationSlowSql slowSql
        {
            get
            {
                return this.slowSqlField;
            }
            set
            {
                this.slowSqlField = value;
            }
        }
        
        public configurationErrorCollector errorCollector
        {
            get
            {
                return this.errorCollectorField;
            }
            set
            {
                this.errorCollectorField = value;
            }
        }
        
        public configurationBrowserMonitoring browserMonitoring
        {
            get
            {
                return this.browserMonitoringField;
            }
            set
            {
                this.browserMonitoringField = value;
            }
        }
        
        public configurationApplicationPools applicationPools
        {
            get
            {
                return this.applicationPoolsField;
            }
            set
            {
                this.applicationPoolsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("ignoreMethod", IsNullable=false)]
        public List<string> threadProfiling
        {
            get
            {
                return this.threadProfilingField;
            }
            set
            {
                this.threadProfilingField = value;
            }
        }
        
        public string labels
        {
            get
            {
                return this.labelsField;
            }
            set
            {
                this.labelsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("add", IsNullable=false)]
        public List<configurationAdd> appSettings
        {
            get
            {
                return this.appSettingsField;
            }
            set
            {
                this.appSettingsField = value;
            }
        }
        
        public configurationUtilization utilization
        {
            get
            {
                return this.utilizationField;
            }
            set
            {
                this.utilizationField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool agentEnabled
        {
            get
            {
                return this.agentEnabledField;
            }
            set
            {
                this.agentEnabledField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool rootAgentEnabled
        {
            get
            {
                return this.rootAgentEnabledField;
            }
            set
            {
                this.rootAgentEnabledField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(80)]
        public int maxStackTraceLines
        {
            get
            {
                return this.maxStackTraceLinesField;
            }
            set
            {
                this.maxStackTraceLinesField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool debugAgent
        {
            get
            {
                return this.debugAgentField;
            }
            set
            {
                this.debugAgentField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool threadProfilingEnabled
        {
            get
            {
                return this.threadProfilingEnabledField;
            }
            set
            {
                this.threadProfilingEnabledField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool crossApplicationTracingEnabled
        {
            get
            {
                return this.crossApplicationTracingEnabledField;
            }
            set
            {
                this.crossApplicationTracingEnabledField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(configurationTimingPrecision.low)]
        public configurationTimingPrecision timingPrecision
        {
            get
            {
                return this.timingPrecisionField;
            }
            set
            {
                this.timingPrecisionField = value;
            }
        }
    }
    
    public partial class configurationService
    {
        
        private configurationServiceProxy proxyField;
        
        private bool sendEnvironmentInfoField;
        
        private string licenseKeyField;
        
        private string hostField;
        
        private System.Nullable<int> portField;
        
        private bool syncStartupField;
        
        private bool autoStartField;
        
        private bool sendDataOnExitField;
        
        private float sendDataOnExitThresholdField;
        
        private System.Nullable<int> requestTimeoutField;
        
        private bool completeTransactionsOnThreadField;
        
        public configurationService()
        {
            this.proxyField = new configurationServiceProxy();
            this.sendEnvironmentInfoField = true;
            this.syncStartupField = false;
            this.autoStartField = true;
            this.sendDataOnExitField = false;
            this.sendDataOnExitThresholdField = ((float)(60000F));
            this.completeTransactionsOnThreadField = false;
        }
        
        public configurationServiceProxy proxy
        {
            get
            {
                return this.proxyField;
            }
            set
            {
                this.proxyField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool sendEnvironmentInfo
        {
            get
            {
                return this.sendEnvironmentInfoField;
            }
            set
            {
                this.sendEnvironmentInfoField = value;
            }
        }
        
        public string licenseKey
        {
            get
            {
                return this.licenseKeyField;
            }
            set
            {
                this.licenseKeyField = value;
            }
        }
        
        public string host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }
        
        public int port
        {
            get
            {
                if (this.portField.HasValue)
                {
                    return this.portField.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                this.portField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool portSpecified
        {
            get
            {
                return this.portField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.portField = null;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool syncStartup
        {
            get
            {
                return this.syncStartupField;
            }
            set
            {
                this.syncStartupField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool autoStart
        {
            get
            {
                return this.autoStartField;
            }
            set
            {
                this.autoStartField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool sendDataOnExit
        {
            get
            {
                return this.sendDataOnExitField;
            }
            set
            {
                this.sendDataOnExitField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "60000")]
        public float sendDataOnExitThreshold
        {
            get
            {
                return this.sendDataOnExitThresholdField;
            }
            set
            {
                this.sendDataOnExitThresholdField = value;
            }
        }
        
        public int requestTimeout
        {
            get
            {
                if (this.requestTimeoutField.HasValue)
                {
                    return this.requestTimeoutField.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                this.requestTimeoutField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requestTimeoutSpecified
        {
            get
            {
                return this.requestTimeoutField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.requestTimeoutField = null;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool completeTransactionsOnThread
        {
            get
            {
                return this.completeTransactionsOnThreadField;
            }
            set
            {
                this.completeTransactionsOnThreadField = value;
            }
        }
    }
    
    public partial class configurationServiceProxy
    {
        
        private string hostField;
        
        private string uriPathField;
        
        private int portField;
        
        private string userField;
        
        private string passwordField;
        
        private string domainField;
        
        public configurationServiceProxy()
        {
            this.portField = 8080;
        }
        
        public string host
        {
            get
            {
                return this.hostField;
            }
            set
            {
                this.hostField = value;
            }
        }
        
        public string uriPath
        {
            get
            {
                return this.uriPathField;
            }
            set
            {
                this.uriPathField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(8080)]
        public int port
        {
            get
            {
                return this.portField;
            }
            set
            {
                this.portField = value;
            }
        }
        
        public string user
        {
            get
            {
                return this.userField;
            }
            set
            {
                this.userField = value;
            }
        }
        
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        public string domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
    }
    
    public partial class configurationApplication
    {
        
        private List<string> nameField;
        
        private bool disableSamplersField;
        
        public configurationApplication()
        {
            this.nameField = new List<string>();
            this.disableSamplersField = false;
        }
        
        public List<string> name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool disableSamplers
        {
            get
            {
                return this.disableSamplersField;
            }
            set
            {
                this.disableSamplersField = value;
            }
        }
    }
    
    public partial class configurationLog
    {
        
        private string levelField;
        
        private string directoryField;
        
        private string fileNameField;
        
        private bool consoleField;
        
        private bool auditLogField;
        
        private System.Nullable<configurationLogFileLockingModel> fileLockingModelField;
        
        public configurationLog()
        {
            this.levelField = "info";
            this.consoleField = false;
            this.auditLogField = false;
        }
        
        [System.ComponentModel.DefaultValueAttribute("info")]
        public string level
        {
            get
            {
                return this.levelField;
            }
            set
            {
                this.levelField = value;
            }
        }
        
        public string directory
        {
            get
            {
                return this.directoryField;
            }
            set
            {
                this.directoryField = value;
            }
        }
        
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool console
        {
            get
            {
                return this.consoleField;
            }
            set
            {
                this.consoleField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool auditLog
        {
            get
            {
                return this.auditLogField;
            }
            set
            {
                this.auditLogField = value;
            }
        }
        
        public configurationLogFileLockingModel fileLockingModel
        {
            get
            {
                if (this.fileLockingModelField.HasValue)
                {
                    return this.fileLockingModelField.Value;
                }
                else
                {
                    return default(configurationLogFileLockingModel);
                }
            }
            set
            {
                this.fileLockingModelField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileLockingModelSpecified
        {
            get
            {
                return this.fileLockingModelField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.fileLockingModelField = null;
                }
            }
        }
    }
    
    public enum configurationLogFileLockingModel
    {
        
        /// <remarks/>
        exclusive,
        
        /// <remarks/>
        minimal,
    }
    
    public partial class configurationInstrumentation
    {
        
        private List<configurationInstrumentationApplication> applicationsField;
        
        private bool logField;
        
        public configurationInstrumentation()
        {
            this.applicationsField = new List<configurationInstrumentationApplication>();
            this.logField = false;
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("application", IsNullable=false)]
        public List<configurationInstrumentationApplication> applications
        {
            get
            {
                return this.applicationsField;
            }
            set
            {
                this.applicationsField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool log
        {
            get
            {
                return this.logField;
            }
            set
            {
                this.logField = value;
            }
        }
    }
    
    public partial class configurationInstrumentationApplication
    {
        
        private string nameField;
        
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    public partial class configurationAttributes
    {
        
        private List<string> includeField;
        
        private List<string> excludeField;
        
        private bool enabledField;
        
        public configurationAttributes()
        {
            this.excludeField = new List<string>();
            this.includeField = new List<string>();
            this.enabledField = true;
        }
        
        public List<string> include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
        
        public List<string> exclude
        {
            get
            {
                return this.excludeField;
            }
            set
            {
                this.excludeField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationParameterGroups
    {
        
        private configurationParameterGroupsIdentityParameters identityParametersField;
        
        private configurationParameterGroupsResponseHeaderParameters responseHeaderParametersField;
        
        private configurationParameterGroupsCustomParameters customParametersField;
        
        private configurationParameterGroupsRequestHeaderParameters requestHeaderParametersField;
        
        public configurationParameterGroups()
        {
            this.requestHeaderParametersField = new configurationParameterGroupsRequestHeaderParameters();
            this.customParametersField = new configurationParameterGroupsCustomParameters();
            this.responseHeaderParametersField = new configurationParameterGroupsResponseHeaderParameters();
            this.identityParametersField = new configurationParameterGroupsIdentityParameters();
        }
        
        public configurationParameterGroupsIdentityParameters identityParameters
        {
            get
            {
                return this.identityParametersField;
            }
            set
            {
                this.identityParametersField = value;
            }
        }
        
        public configurationParameterGroupsResponseHeaderParameters responseHeaderParameters
        {
            get
            {
                return this.responseHeaderParametersField;
            }
            set
            {
                this.responseHeaderParametersField = value;
            }
        }
        
        public configurationParameterGroupsCustomParameters customParameters
        {
            get
            {
                return this.customParametersField;
            }
            set
            {
                this.customParametersField = value;
            }
        }
        
        public configurationParameterGroupsRequestHeaderParameters requestHeaderParameters
        {
            get
            {
                return this.requestHeaderParametersField;
            }
            set
            {
                this.requestHeaderParametersField = value;
            }
        }
    }
    
    public partial class configurationParameterGroupsIdentityParameters
    {
        
        private List<string> ignoreField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationParameterGroupsIdentityParameters()
        {
            this.ignoreField = new List<string>();
        }
        
        public List<string> ignore
        {
            get
            {
                return this.ignoreField;
            }
            set
            {
                this.ignoreField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationParameterGroupsResponseHeaderParameters
    {
        
        private List<string> ignoreField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationParameterGroupsResponseHeaderParameters()
        {
            this.ignoreField = new List<string>();
        }
        
        public List<string> ignore
        {
            get
            {
                return this.ignoreField;
            }
            set
            {
                this.ignoreField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationParameterGroupsCustomParameters
    {
        
        private List<string> ignoreField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationParameterGroupsCustomParameters()
        {
            this.ignoreField = new List<string>();
        }
        
        public List<string> ignore
        {
            get
            {
                return this.ignoreField;
            }
            set
            {
                this.ignoreField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationParameterGroupsRequestHeaderParameters
    {
        
        private List<string> ignoreField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationParameterGroupsRequestHeaderParameters()
        {
            this.ignoreField = new List<string>();
        }
        
        public List<string> ignore
        {
            get
            {
                return this.ignoreField;
            }
            set
            {
                this.ignoreField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationRequestParameters
    {
        
        private List<string> ignoreField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationRequestParameters()
        {
            this.ignoreField = new List<string>();
        }
        
        public List<string> ignore
        {
            get
            {
                return this.ignoreField;
            }
            set
            {
                this.ignoreField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationAnalyticsEvents
    {
        
        private configurationAnalyticsEventsTransactions transactionsField;
        
        private System.Nullable<bool> enabledField;
        
        private System.Nullable<uint> maximumSamplesPerMinuteField;
        
        private System.Nullable<uint> maximumSamplesStoredField;
        
        private System.Nullable<bool> captureAttributesField;
        
        public configurationAnalyticsEvents()
        {
            this.transactionsField = new configurationAnalyticsEventsTransactions();
        }
        
        public configurationAnalyticsEventsTransactions transactions
        {
            get
            {
                return this.transactionsField;
            }
            set
            {
                this.transactionsField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
        
        public uint maximumSamplesPerMinute
        {
            get
            {
                if (this.maximumSamplesPerMinuteField.HasValue)
                {
                    return this.maximumSamplesPerMinuteField.Value;
                }
                else
                {
                    return default(uint);
                }
            }
            set
            {
                this.maximumSamplesPerMinuteField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSamplesPerMinuteSpecified
        {
            get
            {
                return this.maximumSamplesPerMinuteField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.maximumSamplesPerMinuteField = null;
                }
            }
        }
        
        public uint maximumSamplesStored
        {
            get
            {
                if (this.maximumSamplesStoredField.HasValue)
                {
                    return this.maximumSamplesStoredField.Value;
                }
                else
                {
                    return default(uint);
                }
            }
            set
            {
                this.maximumSamplesStoredField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSamplesStoredSpecified
        {
            get
            {
                return this.maximumSamplesStoredField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.maximumSamplesStoredField = null;
                }
            }
        }
        
        public bool captureAttributes
        {
            get
            {
                if (this.captureAttributesField.HasValue)
                {
                    return this.captureAttributesField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.captureAttributesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool captureAttributesSpecified
        {
            get
            {
                return this.captureAttributesField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.captureAttributesField = null;
                }
            }
        }
    }
    
    public partial class configurationAnalyticsEventsTransactions
    {
        
        private System.Nullable<bool> enabledField;
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationCustomEvents
    {
        
        private bool enabledField;
        
        public configurationCustomEvents()
        {
            this.enabledField = true;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationTransactionEvents
    {
        
        private configurationTransactionEventsTransactions transactionsField;
        
        private configurationTransactionEventsAttributes attributesField;
        
        private System.Nullable<bool> enabledField;
        
        private System.Nullable<uint> maximumSamplesPerMinuteField;
        
        private System.Nullable<uint> maximumSamplesStoredField;
        
        public configurationTransactionEvents()
        {
            this.attributesField = new configurationTransactionEventsAttributes();
            this.transactionsField = new configurationTransactionEventsTransactions();
        }
        
        public configurationTransactionEventsTransactions transactions
        {
            get
            {
                return this.transactionsField;
            }
            set
            {
                this.transactionsField = value;
            }
        }
        
        public configurationTransactionEventsAttributes attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
        
        public uint maximumSamplesPerMinute
        {
            get
            {
                if (this.maximumSamplesPerMinuteField.HasValue)
                {
                    return this.maximumSamplesPerMinuteField.Value;
                }
                else
                {
                    return default(uint);
                }
            }
            set
            {
                this.maximumSamplesPerMinuteField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSamplesPerMinuteSpecified
        {
            get
            {
                return this.maximumSamplesPerMinuteField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.maximumSamplesPerMinuteField = null;
                }
            }
        }
        
        public uint maximumSamplesStored
        {
            get
            {
                if (this.maximumSamplesStoredField.HasValue)
                {
                    return this.maximumSamplesStoredField.Value;
                }
                else
                {
                    return default(uint);
                }
            }
            set
            {
                this.maximumSamplesStoredField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maximumSamplesStoredSpecified
        {
            get
            {
                return this.maximumSamplesStoredField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.maximumSamplesStoredField = null;
                }
            }
        }
    }
    
    public partial class configurationTransactionEventsTransactions
    {
        
        private System.Nullable<bool> enabledField;
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationTransactionEventsAttributes
    {
        
        private List<string> includeField;
        
        private List<string> excludeField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationTransactionEventsAttributes()
        {
            this.excludeField = new List<string>();
            this.includeField = new List<string>();
        }
        
        public List<string> include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
        
        public List<string> exclude
        {
            get
            {
                return this.excludeField;
            }
            set
            {
                this.excludeField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationDataTransmission
    {
        
        private bool putForDataSendField;
        
        private configurationDataTransmissionCompressedContentEncoding compressedContentEncodingField;
        
        public configurationDataTransmission()
        {
            this.putForDataSendField = false;
            this.compressedContentEncodingField = configurationDataTransmissionCompressedContentEncoding.deflate;
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool putForDataSend
        {
            get
            {
                return this.putForDataSendField;
            }
            set
            {
                this.putForDataSendField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(configurationDataTransmissionCompressedContentEncoding.deflate)]
        public configurationDataTransmissionCompressedContentEncoding compressedContentEncoding
        {
            get
            {
                return this.compressedContentEncodingField;
            }
            set
            {
                this.compressedContentEncodingField = value;
            }
        }
    }
    
    public enum configurationDataTransmissionCompressedContentEncoding
    {
        
        /// <remarks/>
        deflate,
        
        /// <remarks/>
        gzip,
    }
    
    public partial class configurationTransactionTracer
    {
        
        private configurationTransactionTracerAttributes attributesField;
        
        private string transactionThresholdField;
        
        private configurationTransactionTracerRecordSql recordSqlField;
        
        private int stackTraceThresholdField;
        
        private bool explainEnabledField;
        
        private float explainThresholdField;
        
        private bool enabledField;
        
        private int maxSegmentsField;
        
        private int maxStackTraceField;
        
        private int maxExplainPlansField;
        
        private System.Nullable<bool> captureAttributesField;
        
        public configurationTransactionTracer()
        {
            this.attributesField = new configurationTransactionTracerAttributes();
            this.transactionThresholdField = "apdex_f";
            this.recordSqlField = configurationTransactionTracerRecordSql.obfuscated;
            this.stackTraceThresholdField = 500;
            this.explainEnabledField = false;
            this.explainThresholdField = ((float)(500F));
            this.enabledField = true;
            this.maxSegmentsField = 3000;
            this.maxStackTraceField = 30;
            this.maxExplainPlansField = 20;
        }
        
        public configurationTransactionTracerAttributes attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute("apdex_f")]
        public string transactionThreshold
        {
            get
            {
                return this.transactionThresholdField;
            }
            set
            {
                this.transactionThresholdField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(configurationTransactionTracerRecordSql.obfuscated)]
        public configurationTransactionTracerRecordSql recordSql
        {
            get
            {
                return this.recordSqlField;
            }
            set
            {
                this.recordSqlField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(500)]
        public int stackTraceThreshold
        {
            get
            {
                return this.stackTraceThresholdField;
            }
            set
            {
                this.stackTraceThresholdField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool explainEnabled
        {
            get
            {
                return this.explainEnabledField;
            }
            set
            {
                this.explainEnabledField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(typeof(float), "500")]
        public float explainThreshold
        {
            get
            {
                return this.explainThresholdField;
            }
            set
            {
                this.explainThresholdField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(3000)]
        public int maxSegments
        {
            get
            {
                return this.maxSegmentsField;
            }
            set
            {
                this.maxSegmentsField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(30)]
        public int maxStackTrace
        {
            get
            {
                return this.maxStackTraceField;
            }
            set
            {
                this.maxStackTraceField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(20)]
        public int maxExplainPlans
        {
            get
            {
                return this.maxExplainPlansField;
            }
            set
            {
                this.maxExplainPlansField = value;
            }
        }
        
        public bool captureAttributes
        {
            get
            {
                if (this.captureAttributesField.HasValue)
                {
                    return this.captureAttributesField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.captureAttributesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool captureAttributesSpecified
        {
            get
            {
                return this.captureAttributesField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.captureAttributesField = null;
                }
            }
        }
    }
    
    public partial class configurationTransactionTracerAttributes
    {
        
        private List<string> includeField;
        
        private List<string> excludeField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationTransactionTracerAttributes()
        {
            this.excludeField = new List<string>();
            this.includeField = new List<string>();
        }
        
        public List<string> include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
        
        public List<string> exclude
        {
            get
            {
                return this.excludeField;
            }
            set
            {
                this.excludeField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public enum configurationTransactionTracerRecordSql
    {
        
        /// <remarks/>
        obfuscated,
        
        /// <remarks/>
        raw,
        
        /// <remarks/>
        off,
    }
    
    public partial class configurationDatastoreTracer
    {
        
        private configurationDatastoreTracerInstanceReporting instanceReportingField;
        
        private configurationDatastoreTracerDatabaseNameReporting databaseNameReportingField;
        
        public configurationDatastoreTracer()
        {
            this.databaseNameReportingField = new configurationDatastoreTracerDatabaseNameReporting();
            this.instanceReportingField = new configurationDatastoreTracerInstanceReporting();
        }
        
        public configurationDatastoreTracerInstanceReporting instanceReporting
        {
            get
            {
                return this.instanceReportingField;
            }
            set
            {
                this.instanceReportingField = value;
            }
        }
        
        public configurationDatastoreTracerDatabaseNameReporting databaseNameReporting
        {
            get
            {
                return this.databaseNameReportingField;
            }
            set
            {
                this.databaseNameReportingField = value;
            }
        }
    }
    
    public partial class configurationDatastoreTracerInstanceReporting
    {
        
        private bool enabledField;
        
        public configurationDatastoreTracerInstanceReporting()
        {
            this.enabledField = true;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationDatastoreTracerDatabaseNameReporting
    {
        
        private bool enabledField;
        
        public configurationDatastoreTracerDatabaseNameReporting()
        {
            this.enabledField = true;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationCrossApplicationTracer
    {
        
        private bool enabledField;
        
        public configurationCrossApplicationTracer()
        {
            this.enabledField = true;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationHighSecurity
    {
        
        private bool enabledField;
        
        public configurationHighSecurity()
        {
            this.enabledField = false;
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationLiveInstrumentation
    {
        
        private bool enabledField;
        
        public configurationLiveInstrumentation()
        {
            this.enabledField = true;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationStripExceptionMessages
    {
        
        private bool enabledField;
        
        public configurationStripExceptionMessages()
        {
            this.enabledField = false;
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationSlowSql
    {
        
        private bool enabledField;
        
        public configurationSlowSql()
        {
            this.enabledField = true;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
    }
    
    public partial class configurationErrorCollector
    {
        
        private configurationErrorCollectorIgnoreErrors ignoreErrorsField;
        
        private configurationErrorCollectorIgnoreStatusCodes ignoreStatusCodesField;
        
        private configurationErrorCollectorAttributes attributesField;
        
        private bool enabledField;
        
        private System.Nullable<bool> captureAttributesField;
        
        private bool captureEventsField;
        
        private int maxEventSamplesStoredField;
        
        public configurationErrorCollector()
        {
            this.attributesField = new configurationErrorCollectorAttributes();
            this.ignoreStatusCodesField = new configurationErrorCollectorIgnoreStatusCodes();
            this.ignoreErrorsField = new configurationErrorCollectorIgnoreErrors();
            this.enabledField = true;
            this.captureEventsField = true;
            this.maxEventSamplesStoredField = 100;
        }
        
        public configurationErrorCollectorIgnoreErrors ignoreErrors
        {
            get
            {
                return this.ignoreErrorsField;
            }
            set
            {
                this.ignoreErrorsField = value;
            }
        }
        
        public configurationErrorCollectorIgnoreStatusCodes ignoreStatusCodes
        {
            get
            {
                return this.ignoreStatusCodesField;
            }
            set
            {
                this.ignoreStatusCodesField = value;
            }
        }
        
        public configurationErrorCollectorAttributes attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool enabled
        {
            get
            {
                return this.enabledField;
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        public bool captureAttributes
        {
            get
            {
                if (this.captureAttributesField.HasValue)
                {
                    return this.captureAttributesField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.captureAttributesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool captureAttributesSpecified
        {
            get
            {
                return this.captureAttributesField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.captureAttributesField = null;
                }
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool captureEvents
        {
            get
            {
                return this.captureEventsField;
            }
            set
            {
                this.captureEventsField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(100)]
        public int maxEventSamplesStored
        {
            get
            {
                return this.maxEventSamplesStoredField;
            }
            set
            {
                this.maxEventSamplesStoredField = value;
            }
        }
    }
    
    public partial class configurationErrorCollectorIgnoreErrors
    {
        
        private List<string> exceptionField;
        
        public configurationErrorCollectorIgnoreErrors()
        {
            this.exceptionField = new List<string>();
        }
        
        public List<string> exception
        {
            get
            {
                return this.exceptionField;
            }
            set
            {
                this.exceptionField = value;
            }
        }
    }
    
    public partial class configurationErrorCollectorIgnoreStatusCodes
    {
        
        private List<float> codeField;
        
        public configurationErrorCollectorIgnoreStatusCodes()
        {
            this.codeField = new List<float>();
        }
        
        public List<float> code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
    }
    
    public partial class configurationErrorCollectorAttributes
    {
        
        private List<string> includeField;
        
        private List<string> excludeField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationErrorCollectorAttributes()
        {
            this.excludeField = new List<string>();
            this.includeField = new List<string>();
        }
        
        public List<string> include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
        
        public List<string> exclude
        {
            get
            {
                return this.excludeField;
            }
            set
            {
                this.excludeField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationBrowserMonitoring
    {
        
        private List<configurationBrowserMonitoringPath> requestPathsExcludedField;
        
        private configurationBrowserMonitoringAttributes attributesField;
        
        private bool autoInstrumentField;
        
        private string loaderField;
        
        private bool sslForHttpField;
        
        private System.Nullable<bool> captureAttributesField;
        
        public configurationBrowserMonitoring()
        {
            this.attributesField = new configurationBrowserMonitoringAttributes();
            this.requestPathsExcludedField = new List<configurationBrowserMonitoringPath>();
            this.autoInstrumentField = true;
            this.loaderField = "rum";
            this.sslForHttpField = false;
        }
        
        [System.Xml.Serialization.XmlArrayItemAttribute("path", IsNullable=false)]
        public List<configurationBrowserMonitoringPath> requestPathsExcluded
        {
            get
            {
                return this.requestPathsExcludedField;
            }
            set
            {
                this.requestPathsExcludedField = value;
            }
        }
        
        public configurationBrowserMonitoringAttributes attributes
        {
            get
            {
                return this.attributesField;
            }
            set
            {
                this.attributesField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool autoInstrument
        {
            get
            {
                return this.autoInstrumentField;
            }
            set
            {
                this.autoInstrumentField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute("rum")]
        public string loader
        {
            get
            {
                return this.loaderField;
            }
            set
            {
                this.loaderField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool sslForHttp
        {
            get
            {
                return this.sslForHttpField;
            }
            set
            {
                this.sslForHttpField = value;
            }
        }
        
        public bool captureAttributes
        {
            get
            {
                if (this.captureAttributesField.HasValue)
                {
                    return this.captureAttributesField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.captureAttributesField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool captureAttributesSpecified
        {
            get
            {
                return this.captureAttributesField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.captureAttributesField = null;
                }
            }
        }
    }
    
    public partial class configurationBrowserMonitoringPath
    {
        
        private string regexField;
        
        public string regex
        {
            get
            {
                return this.regexField;
            }
            set
            {
                this.regexField = value;
            }
        }
    }
    
    public partial class configurationBrowserMonitoringAttributes
    {
        
        private List<string> includeField;
        
        private List<string> excludeField;
        
        private System.Nullable<bool> enabledField;
        
        public configurationBrowserMonitoringAttributes()
        {
            this.excludeField = new List<string>();
            this.includeField = new List<string>();
        }
        
        public List<string> include
        {
            get
            {
                return this.includeField;
            }
            set
            {
                this.includeField = value;
            }
        }
        
        public List<string> exclude
        {
            get
            {
                return this.excludeField;
            }
            set
            {
                this.excludeField = value;
            }
        }
        
        public bool enabled
        {
            get
            {
                if (this.enabledField.HasValue)
                {
                    return this.enabledField.Value;
                }
                else
                {
                    return default(bool);
                }
            }
            set
            {
                this.enabledField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool enabledSpecified
        {
            get
            {
                return this.enabledField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.enabledField = null;
                }
            }
        }
    }
    
    public partial class configurationApplicationPools
    {
        
        private configurationApplicationPoolsDefaultBehavior defaultBehaviorField;
        
        private List<configurationApplicationPoolsApplicationPool> applicationPoolField;
        
        public configurationApplicationPools()
        {
            this.applicationPoolField = new List<configurationApplicationPoolsApplicationPool>();
            this.defaultBehaviorField = new configurationApplicationPoolsDefaultBehavior();
        }
        
        public configurationApplicationPoolsDefaultBehavior defaultBehavior
        {
            get
            {
                return this.defaultBehaviorField;
            }
            set
            {
                this.defaultBehaviorField = value;
            }
        }
        
        public List<configurationApplicationPoolsApplicationPool> applicationPool
        {
            get
            {
                return this.applicationPoolField;
            }
            set
            {
                this.applicationPoolField = value;
            }
        }
    }
    
    public partial class configurationApplicationPoolsDefaultBehavior
    {
        
        private bool instrumentField;
        
        public bool instrument
        {
            get
            {
                return this.instrumentField;
            }
            set
            {
                this.instrumentField = value;
            }
        }
    }
    
    public partial class configurationApplicationPoolsApplicationPool
    {
        
        private string nameField;
        
        private bool instrumentField;
        
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        public bool instrument
        {
            get
            {
                return this.instrumentField;
            }
            set
            {
                this.instrumentField = value;
            }
        }
    }
    
    public partial class configurationAdd
    {
        
        private string keyField;
        
        private string valueField;
        
        public string key
        {
            get
            {
                return this.keyField;
            }
            set
            {
                this.keyField = value;
            }
        }
        
        public string value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    public partial class configurationUtilization
    {
        
        private bool detectAwsField;
        
        private bool detectAzureField;
        
        private bool detectGcpField;
        
        private bool detectPcfField;
        
        private bool detectDockerField;
        
        private System.Nullable<int> logicalProcessorsField;
        
        private System.Nullable<int> totalRamMibField;
        
        private string billingHostField;
        
        public configurationUtilization()
        {
            this.detectAwsField = true;
            this.detectAzureField = true;
            this.detectGcpField = true;
            this.detectPcfField = true;
            this.detectDockerField = true;
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool detectAws
        {
            get
            {
                return this.detectAwsField;
            }
            set
            {
                this.detectAwsField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool detectAzure
        {
            get
            {
                return this.detectAzureField;
            }
            set
            {
                this.detectAzureField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool detectGcp
        {
            get
            {
                return this.detectGcpField;
            }
            set
            {
                this.detectGcpField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool detectPcf
        {
            get
            {
                return this.detectPcfField;
            }
            set
            {
                this.detectPcfField = value;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(true)]
        public bool detectDocker
        {
            get
            {
                return this.detectDockerField;
            }
            set
            {
                this.detectDockerField = value;
            }
        }
        
        public int logicalProcessors
        {
            get
            {
                if (this.logicalProcessorsField.HasValue)
                {
                    return this.logicalProcessorsField.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                this.logicalProcessorsField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool logicalProcessorsSpecified
        {
            get
            {
                return this.logicalProcessorsField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.logicalProcessorsField = null;
                }
            }
        }
        
        public int totalRamMib
        {
            get
            {
                if (this.totalRamMibField.HasValue)
                {
                    return this.totalRamMibField.Value;
                }
                else
                {
                    return default(int);
                }
            }
            set
            {
                this.totalRamMibField = value;
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool totalRamMibSpecified
        {
            get
            {
                return this.totalRamMibField.HasValue;
            }
            set
            {
                if (value==false)
                {
                    this.totalRamMibField = null;
                }
            }
        }
        
        public string billingHost
        {
            get
            {
                return this.billingHostField;
            }
            set
            {
                this.billingHostField = value;
            }
        }
    }
    
    public enum configurationTimingPrecision
    {
        
        /// <remarks/>
        high,
        
        /// <remarks/>
        low,
    }
}
