FROM ubuntu:14.04

WORKDIR /root
RUN mkdir mvc
WORKDIR /root/mvc

RUN apt-get update
RUN apt-get install -y \
    curl \
    libc++1 \
    apt-transport-https

RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
RUN mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
RUN sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'

RUN apt-get update

RUN apt-get install -y dotnet-sdk-2.0.0

RUN dotnet new mvc && \
    dotnet restore && \
    dotnet build

EXPOSE 5000

ENV CORECLR_ENABLE_PROFILING=1
ENV CORECLR_PROFILER={36032161-FFC0-4B61-B559-F6C5D41BAE5A}
ENV CORECLR_PROFILER_PATH=/profiler/libNewRelicProfiler.so
ENV CORECLR_NEWRELIC_HOME=/agent
ENV NEW_RELIC_HOST=staging-collector.newrelic.com
ENV NEW_RELIC_LICENSE_KEY="b25fd3ca20fe323a9a7c4a092e48d62dc64cc61d"