//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("NewRelic.Api.Agent")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("New Relic .NET Agent API")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("6.25.0.15")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("6.25.0.15")]
[assembly: System.Reflection.AssemblyProductAttribute("New Relic .NET Agent")]
[assembly: System.Reflection.AssemblyTitleAttribute("NewRelic.Api.Agent")]
[assembly: System.Reflection.AssemblyVersionAttribute("6.50.0.0")]

// Generated by the MSBuild WriteCodeFragment class.

