name: Build the Build Tools solution

on:
  pull_request:
    branches:
      - main
    paths:
      - 'build/**'
      - '.github/workflows/scripts/**'

  workflow_dispatch:

permissions:
  contents: read

jobs:
    build:
      runs-on: windows-latest
  
      steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Install latest .NET 10 SDK
        uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'ga'

      - name: Build the solution
        run:  dotnet build build/BuildTools.sln -c Release -m -p:Platform="Any CPU" --restore
