# This workflow builds and pushes Docker images for each service in docker-compose.yml to Azure Container Registry
# ACR: dotnetunboundedservices-dhgfaedgcsdfb5bh

name: Build, Push and Deploy UnboundedServices Containers

on:
  push:
    paths:
      - 'tests/Agent/IntegrationTests/UnboundedServices/docker-compose.yml'
      - '.github/workflows/build-and-push-containers.yml'
      - 'tests/Agent/IntegrationTests/UnboundedServices/**'
  workflow_dispatch:
    inputs:
      services:
        description: 'Comma-separated list of services to build and deploy (leave blank for all). Valid values: couchbase, postgres, mssql, mysql, rabbitmq, mongodb32, mongodb60, oracle, elastic, elastic7.'
        required: false
        default: ''

permissions:
  contents: read
  id-token: write
  actions: read
  pull-requests: read

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix based on input
        id: set-matrix
        run: |
          ALL_SERVICES=(couchbase postgres mssql mysql rabbitmq mongodb32 mongodb60 oracle elastic elastic7)
          if [ -z "${{ github.event.inputs.services }}" ]; then
            SELECTED=("${ALL_SERVICES[@]}")
          else
            IFS=',' read -ra SELECTED <<< "${{ github.event.inputs.services }}"
            # Trim whitespace
            for i in "${!SELECTED[@]}"; do
              SELECTED[$i]="$(echo \"${SELECTED[$i]}\" | xargs)"
            done
          fi
          # Build JSON array
          JSON_MATRIX=$(printf '%s\n' "${SELECTED[@]}" | jq -R . | jq -s '{service: .}')
          echo "matrix=$JSON_MATRIX" >> $GITHUB_OUTPUT

  build-and-deploy:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
    permissions:
      contents: read
      id-token: write
      actions: read
      pull-requests: read
    env:
      REGISTRY: ${{ secrets.REGISTRY_LOGIN_SERVER }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          disable-sudo: true
          egress-policy: audit
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Azure Login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2.3.0
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Container Registry Login
        uses: azure/docker-login@15c4aadf093404726ab2ff205b2cdd33fa6d054c # v2.0.0
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Set service config
        id: config
        run: |
          case "${{ matrix.service }}" in
            couchbase)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/couchbase" >> $GITHUB_OUTPUT
              echo "tag=couchbase:latest" >> $GITHUB_OUTPUT
              echo "ports=8091,8092,8093,8094,8095,11210" >> $GITHUB_OUTPUT
              echo "memory=3.0" >> $GITHUB_OUTPUT
              echo "env=COUCHBASE_ADMINISTRATOR_PASSWORD=${{ secrets.COUCHBASE_ADMINISTRATOR_PASSWORD }}" >> $GITHUB_OUTPUT
              ;;
            postgres)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/postgres" >> $GITHUB_OUTPUT
              echo "tag=postgres:latest" >> $GITHUB_OUTPUT
              echo "ports=5432" >> $GITHUB_OUTPUT
              echo "env=POSTGRES_USER=postgres\nPOSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> $GITHUB_OUTPUT
              ;;
            mssql)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/mssql" >> $GITHUB_OUTPUT
              echo "tag=mssql:latest" >> $GITHUB_OUTPUT
              echo "ports=1433" >> $GITHUB_OUTPUT
              echo "env=SA_PASSWORD=${{ secrets.MSSQL_SA_PASSWORD }}" >> $GITHUB_OUTPUT
              ;;
            mysql)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/mysql" >> $GITHUB_OUTPUT
              echo "tag=mysql:latest" >> $GITHUB_OUTPUT
              echo "ports=3306" >> $GITHUB_OUTPUT
              echo "command=mysqld --default-authentication-plugin=mysql_native_password" >> $GITHUB_OUTPUT
              echo "env=MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_OUTPUT
              ;;
            rabbitmq)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/rabbitmq" >> $GITHUB_OUTPUT
              echo "tag=rabbitmq:latest" >> $GITHUB_OUTPUT
              echo "ports=5671,5672,15671,15672" >> $GITHUB_OUTPUT
              echo "command=rabbitmq-plugins enable --offline rabbitmq_management && rabbitmq-server" >> $GITHUB_OUTPUT
              echo "env=RABBITMQ_DEFAULT_USER=${{ secrets.RABBITMQ_DEFAULT_USER }}\nRABBITMQ_DEFAULT_PASS=${{ secrets.RABBITMQ_DEFAULT_PASS }}" >> $GITHUB_OUTPUT
              ;;
            mongodb32)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/mongodb32" >> $GITHUB_OUTPUT
              echo "tag=mongodb32:latest" >> $GITHUB_OUTPUT
              echo "ports=27017" >> $GITHUB_OUTPUT
              echo "env=MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}\nMONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> $GITHUB_OUTPUT
              ;;
            mongodb60)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/mongodb60" >> $GITHUB_OUTPUT
              echo "tag=mongodb60:latest" >> $GITHUB_OUTPUT
              echo "ports=27017" >> $GITHUB_OUTPUT
              echo "env=MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}\nMONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}" >> $GITHUB_OUTPUT
              ;;
            oracle)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/oracle" >> $GITHUB_OUTPUT
              echo "tag=oracle:latest" >> $GITHUB_OUTPUT
              echo "ports=1521" >> $GITHUB_OUTPUT
              echo "env=ORACLE_PWD=${{ secrets.ORACLE_PWD }}" >> $GITHUB_OUTPUT
              ;;
            elastic)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/elastic" >> $GITHUB_OUTPUT
              echo "tag=elastic:latest" >> $GITHUB_OUTPUT
              echo "ports=9200" >> $GITHUB_OUTPUT
              echo "memory=2.0" >> $GITHUB_OUTPUT
              echo "env=discovery.type=single-node\nELASTIC_PASSWORD=${{ secrets.ELASTIC_PASSWORD }}\nxpack.security.enabled=true\nxpack.security.http.ssl.enabled=false" >> $GITHUB_OUTPUT
              ;;
            elastic7)
              echo "context=tests/Agent/IntegrationTests/UnboundedServices/elastic7" >> $GITHUB_OUTPUT
              echo "tag=elastic7:latest" >> $GITHUB_OUTPUT
              echo "ports=9201" >> $GITHUB_OUTPUT
              echo "memory=2.0" >> $GITHUB_OUTPUT
              echo "env=discovery.type=single-node\nELASTIC_PASSWORD=${{ secrets.ELASTIC_PASSWORD }}\nxpack.security.enabled=true\nxpack.security.http.ssl.enabled=false" >> $GITHUB_OUTPUT
              ;;
          esac
      - name: Build and push ${{ matrix.service }} image
        uses: docker/build-push-action@1dc73863535b631f98b2378be8619f83b136f4a0 # v6.17.0
        with:
          context: ${{ steps.config.outputs.context }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ steps.config.outputs.tag }}
      - name: Deploy ${{ matrix.service }} to Azure Container Instance
        uses: azure/aci-deploy@28cafb864979bc5b44cd1f3fd45522727eb5a3db # v1.1.3
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          location: ${{ secrets.AZURE_LOCATION }}
          dns-name-label: dotnet-unboundedservices-${{ matrix.service }}-server
          name: ${{ matrix.service }}-server
          image: ${{ env.REGISTRY }}/${{ steps.config.outputs.tag }}
          registry-login-server: ${{ env.REGISTRY }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          ports: ${{ steps.config.outputs.ports }}
          memory: ${{ steps.config.outputs.memory }}
          command-line: ${{ steps.config.outputs.command }}
          environment-variables: ${{ steps.config.outputs.env }}
