name: Build the Build Tools solution

on:
  pull_request:
    branches:
      - main
    paths:
      - 'build/**'
      - '.github/workflows/scripts/**'

  workflow_dispatch:

permissions:
  contents: read

jobs:
    build:
      runs-on: windows-latest
  
      steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install latest .NET 10 SDK
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: '10.0.x'
          dotnet-quality: 'ga'

      - name: Build the solution
        run:  dotnet build build/BuildTools.sln -c Release -m -p:Platform="Any CPU" --restore
