name: Call S3 Indexer

on:
  workflow_dispatch:
  push:
    branches:
      - 'tippmar-nr/call-s3-indexer-workflow'

jobs:
  index-download-site:
    name: Rebuild indexes on the download site
#    if: ${{ github.event.inputs.downloadsite == 'true' }} 
    uses: ./.github/workflows/build_download_site_index_files.yml
    with:
#      bucket: "${{ secrets.BUCKET_NAME }}"
      bucket: "nr-downloads-main"
      prefix: "dot_net_agent/latest_release"
      aws-region: "us-east-1"
      dry-run: true
    secrets: inherit
    