name: Call S3 Indexer In Another Repo

on:
  workflow_dispatch:
  push:
    branches:
      - 'tippmar-nr/call-s3-indexer-workflow'

jobs:
  call-s3-indexer-workflow-passing-data:
    uses: newrelic/s3-indexer/.github/workflows/s3-indexer.yml@7362e8365054598fd9be36129269d83f4a41334b
    with:
      bucket: 'nr-downloads-main'
      prefix: 'dot_net_agent'
      aws-region: 'us-east-1'
      dry-run: true
    secrets:
      inherit
    