name: Call S3 Indexer In Another Repo

on:
  workflow_dispatch:
  push:
    branches:
      - 'tippmar-nr/call-s3-indexer-workflow'

jobs:
  index-download-site:
    name: Rebuild indexes on the download site
#    if: ${{ github.event.inputs.downloadsite == 'true' }} 
    runs-on: ubuntu-latest
    steps:
      - name: Build indexes for latest_release
        uses: ./.github/workflows/build_download_site_index_files.yml
        with:
          bucket: ${{ secrets.BUCKET_NAME }}
          prefix: "dot_net_agent/latest_release"
          aws-region: "us-east-1"
          dry-run: true
      - name: Build indexes for previous_release
        uses: ./.github/workflows/build_download_site_index_files.yml
        with:
          bucket: ${{ secrets.BUCKET_NAME }}
          prefix: "dot_net_agent/previous_releases/${{ github.event.inputs.agent_version }}"
          aws-region: "us-east-1"
          dry-run: true
    
    