name: Call S3 Indexer

on:
  workflow_dispatch:
  push:
    branches:
      - 'tippmar-nr/call-s3-indexer-workflow'

jobs:
  index-download-site:
    name: Rebuild indexes on the download site
    uses: ./.github/workflows/build_download_site_index_files.yml
    strategy:
      matrix:
        prefix: ["dot_net_agent/latest_release", "dot_net_agent/previous_releases/10.7.0"]
    with:
      prefix: ${{ matrix.prefix }}
      aws-region: "us-east-1"
      dry-run: true
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      MT_TEST_BUCKET_NAME: ${{ secrets.MT_TEST_BUCKET_NAME }}

    