name: Deploy the .NET New Relic Lambda Tracer

on:
  workflow_dispatch:
    inputs:
      run_id:
        description: 'Run ID of the Release Workflow (awslambda_release.yml) that was triggered by creating a Release in GitHub.  ID can be found in URL for run.'
        required: true
      deploy:
        description: 'If "true", deploy the artifacts. If "false", do everything except deploy.'
        required: true
        default: 'false'

env:
  DOTNET_NOLOGO: true

permissions:
  contents: read

jobs:

  get-external-artifacts:
    permissions:
      actions: read  # for dawidd6/action-download-artifact to query and download artifacts
      pull-requests: read  # for dawidd6/action-download-artifact to query commit hash
    name: Get and Publish Deploy Artifacts Locally
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
        with:
          egress-policy: audit 

      - name: Download Deploy Artifacts
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615 # v2.27.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: awslambda_release.yml
          run_id: ${{ github.event.inputs.run_id }}
          name: deploy-artifacts
          path: ${{ github.workspace }}
          repo: ${{ github.repository }}
      
      - name: Upload Deploy Artifacts Locally
        uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
        with:
          name: deploy-artifacts
          path: ${{ github.workspace }}
          if-no-files-found: error
  
  deploy-nuget:
    needs: get-external-artifacts
    name: Deploy to NuGet
    runs-on: windows-2019

    env:
      nuget_source: https://www.nuget.org

    steps:
      - name: Download Deploy Artifacts
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
        with:
          name: deploy-artifacts
          path: ${{ github.workspace }}\working_dir

      - name: Setup NuGet API Key
        run: |
          nuget.exe setApiKey ${{ secrets.NUGET_APIKEY }} -Source ${{ env.nuget_source }}
        shell: pwsh

      - name: Deploy .NET New Relic Lambda Tracer to Nuget
        run: |
          $packageName = Get-ChildItem ${{ github.workspace }}\working_dir\NugetAwsLambdaOpenTracer\NewRelic.OpenTracing.AmazonLambda.Tracer.*.nupkg -Name
          $packagePath = Convert-Path ${{ github.workspace }}\working_dir\NugetAwsLambdaOpenTracer\$packageName
          if ("${{ github.event.inputs.deploy }}" -eq "true") {
            nuget.exe push $packagePath -Source ${{ env.nuget_source }}
          }
          else {
            Write-Host "Input:deploy was not true (${{ github.event.inputs.deploy }}).  The following deploy command was not run:"
            Write-Host "nuget.exe push $packagePath -Source ${{ env.nuget_source }}"
          }
        shell: powershell
