name: Release Please

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**" # skip changes to the .github branch (workflows, etc.)
  workflow_dispatch:
  
permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          disable-sudo: true
          egress-policy: audit

      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.DOTNET_AGENT_GH_TOKEN }}
          config-file: release-please/release-please-config.json
          manifest-file: release-please/.release-please-manifest.json