name: Unit Tests and Code Coverage

on:
  pull_request:
    branches:
      - main
      - "feature/**"
  
  # needs to run on every push to main to keep CodeCov in sync
  push:
    branches:
      - main
      
  workflow_dispatch: # allows for manual trigger

env:
  DOTNET_NOLOGO: true
  NR_DEV_BUILD_HOME: false


# only allow one instance of this workflow to be running per PR or branch, cancels any that are already running
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-modified-files:
    name: Check if source files were modified, skip remaining jobs if not
    uses: ./.github/workflows/check_modified_files.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read

  run-unit-tests:
    name: Run Unit Tests
    needs: check-modified-files
    runs-on: windows-latest

    # don't run this job if triggered by Dependabot, will cause all other jobs to be skipped as well
    # run this job if source files were modified, or if triggered by a manual execution or by a push (not a PR)
    if: github.actor != 'dependabot[bot]' && (needs.check-modified-files.outputs.source-files-changed == 'true' ||  github.event_name == 'workflow_dispatch' || github.event_name == 'push')

    env:
      test_results_path: tests\TestResults

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Restore NuGet Packages
        run: dotnet restore

      - name: Build & Run Unit Tests
        run: dotnet test --verbosity minimal --no-restore --settings tests\UnitTests.runsettings --results-directory ${{ env.test_results_path }}

      - name: Upload coverage reports to Codecov.io
        uses: codecov/codecov-action@fdcc8476540edceab3de004e990f80d881c6cc00 # v5.5.0
        with:
            flags: Agent
            directory: ${{ env.test_results_path }}
            token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
            name: UnitTestResults # Artifact name        
            path: ${{ env.test_results_path }} # Directory containing files to upload
